/// The role of a chat message participant.
enum ChatRole {
  system('system'),
  user('user'),
  assistant('assistant'),
  tool('tool');

  final String value;
  const ChatRole(this.value);
}

/// Represents a tool invocation request from the language model.
class ToolCall {
  /// The unique call identifier generated by the model.
  final String id;

  /// The name of the tool function to call.
  final String name;

  /// The parsed or raw arguments map.
  final Map<String, dynamic> arguments;

  const ToolCall({
    required this.id,
    required this.name,
    required this.arguments,
  });

  Map<String, dynamic> toMap() => {
    'id': id,
    'type': 'function',
    'function': {'name': name, 'arguments': arguments},
  };
}

/// Represents a single message in a chat sequence.
class ChatMessage {
  final ChatRole role;
  final String content;
  final String? name;
  final List<ToolCall>? toolCalls;
  final String? toolCallId;

  const ChatMessage({
    required this.role,
    required this.content,
    this.name,
    this.toolCalls,
    this.toolCallId,
  });

  /// Factory for a system message.
  factory ChatMessage.system(String content) =>
      ChatMessage(role: ChatRole.system, content: content);

  /// Factory for a user message.
  factory ChatMessage.user(String content) =>
      ChatMessage(role: ChatRole.user, content: content);

  /// Factory for an assistant response message.
  factory ChatMessage.assistant(String content, {List<ToolCall>? toolCalls}) =>
      ChatMessage(
        role: ChatRole.assistant,
        content: content,
        toolCalls: toolCalls,
      );

  /// Factory for a tool result message.
  factory ChatMessage.tool({
    required String toolCallId,
    required String content,
    String? name,
  }) => ChatMessage(
    role: ChatRole.tool,
    content: content,
    toolCallId: toolCallId,
    name: name,
  );

  Map<String, dynamic> toMap() => {
    'role': role.value,
    'content': content,
    if (name != null) 'name': name,
    if (toolCalls != null)
      'tool_calls': toolCalls!.map((e) => e.toMap()).toList(),
    if (toolCallId != null) 'tool_call_id': toolCallId,
  };

  @override
  String toString() => 'ChatMessage(role: ${role.value}, content: $content)';
}
